### PR TITLE
Replace pos-tip by popup.el

### LINKED ISSUE #1: `pos-tip` uses `x-display-pixel-width`, which isn't defined if Emacs isn't compiled with X support
Hey there!

I would love to use your small package, that looks neat, but I get the following error whenever I put my cursor on an line highlighted by `flymake`:

```
Error running timer ‘flymake-diagnostic-at-point-maybe-display’: (void-function pop-tip-show)
```

GNU Emacs 26.1, no X, HEAD on your repository as well as `pos-tip`.

### PR DESCRIPTION
**Pull request by ramnes**
Fixes #1.

### CODE REVIEW

**Comment by ramnes** [comment]
> Would you find it acceptable to set flymake-diagnostic-at-point-display-diagnostic-function in your configuration to your preferred popup library instead?

Yeaaaaah… that would work. Althought I'm not sure if you really want to deal with that on your side; this is pretty boring as a maintainer, even more if the API between the different libraries end up being different. And then you'd also have to either remove the dependency to `pos-tip` but explain to everyone that they must choose a library to handle this, or keep it as a dependency but then all the guys like me that want to use another library will have an useless dependency in their config tree… 

> the second introduces a change I'm reluctant to make. pos-tip and popup.el are quite different (at least on macOS), and I prefer the former to the latter.

What is it that you prefer with `pos-tip`, is it the style? If so, I'm pretty sure we could get `popup.el` to mimic `pos-tip` style, since you can set popup faces. It would just require one or two more lines.

Last but not least, don't forget that I'm pretty much advocating for `popup.el` only because `pos-tip` does not work on my setup; and given the error, I doubt that I'll be the only one to come and say this if that package gets more users. :wink:

**Comment by ramnes** [comment]
Also, I've rebased on your master branch so that this PR only has the second commit anymore. Sorry, I meant to do two different pull request at the beginning, but then realized that I didn't make a branch for the first commit and that I opened the PR based on my master branch… so here we are. :smile:

**Comment by meqif** [comment]
Thanks for rebasing.

> What is it that you prefer with pos-tip, is it the style?

It's not just the style, pos-tip is a tooltip, as opposed to a "full" popup with its own floating frame, and is rendered in an entirely different way (thus requiring a window server).

 As you can see in the screenshots above, popup.el is a little buggy: notice how the first line exceeds the width of the rest of the popup box. Because of that, at one point this package used [posframe](https://github.com/tumashu/posframe) instead, but it also suffered from some annoying bugs.

That said, you convinced me to accept your patch. I can follow my own advice and use pos-tip in my personal configuration. 😉 

Thanks for your contribution!

**Comment by ramnes** [comment]
Thank you very much for your understanding. I hope you didn't feel like I was trying to force your hand!

**Comment by meqif** [comment]
Not at all, this was a completely reasonable change. 🙂

**Pull request merged**
